version: "3"
services:
  app:
    cpus: 2
    mem_limit: 4g
    # build:  # build context is used when developing locally
    #   context: ..
    #   dockerfile: ./.devcontainer/Dockerfile
    image: datajoint/datajoint_tutorials:latest
    extra_hosts:
      - fakeservices.datajoint.io:127.0.0.1
    volumes:
      - ..:/workspaces/datajoint-tutorials:cached
      - docker_data:/var/lib/docker  # persist docker images
    privileged: true # only because of dind
volumes:
  docker_data: